### ISSUE TITLE
Can't call $RefParser in java 11

### ISSUE THREAD

**Issue by ntthaibk** [ZenWave360/json-schema-ref-parser-jvm#1]
I still can call another class in the package that's not start with $ sign. Maybe that's an issue?

**Comment by ivangsa** [comment]
hi @ntthaibk 

I'm using $RefParser sucessfully in java 11 and 17 inside all tests in this project 
https://github.com/ZenWave360/json-schema-ref-parser-jvm/blob/main/src/test/java/io/zenwave360/jsonrefparser/ParserTest.java

and also as dependency in this other project 

https://github.com/ZenWave360/zenwave-code-generator/blob/main/zenwave-code-generator-cli/src/main/java/io/zenwave360/generator/parsers/DefaultYamlParser.java#L46

Maybe if you provide more details I can help..

I'm closing this issue now, but feel free to reopen it with more details

Thanks (and sorry for the delay answering...)
