### ISSUE TITLE
[bug] Parser is not working when using json from string source instead of file/classpath

### ISSUE THREAD

**Issue by JRDG** [ZenWave360/json-schema-ref-parser-jvm#2]
Hi! I encounter a bug while using the library, it seems that, despite[ having a constructor allowing you to use a string variable](https://github.com/ZenWave360/json-schema-ref-parser-jvm/blob/main/src/main/java/io/zenwave360/jsonrefparser/%24RefParser.java#L73) as the json source:

```java
public $RefParser(String json) {
        this.json = json;
        this.file = null;
        this.uri = null;
    }
```

It is not working properly when executing `.dereference()` method.

Expected result:
- Json is parsed without errors

Actual result:
- Null pointer exception
```log
java.lang.NullPointerException: null
--
at io.zenwave360.jsonrefparser.$RefParser.dereference($RefParser.java:203) ~[json-schema-ref-parser-jvm-0.8.1.jar:?]
at io.zenwave360.jsonrefparser.$RefParser.dereference($RefParser.java:130) ~[json-schema-ref-parser-jvm-0.8.1.jar:?]
```

Caused by:
- When using json string constructor, the variable `this.uri` is null and errors occurs on `$RefParser.java:203`:`currentFileURL.toString()`

How to reproduce:
- Create a $RefParser object using `public $RefParser(String json)` constructor
- Call `.dereference()` method.

Possible solutions:
- Assigning a dummy URI object to `this.uri` could solve the problem, under `parse()` method, something like **(not tested)**:
  - from:
  ```java
       public $RefParser parse() throws IOException {
              if(file != null) {
                  refs = new $Refs(Parser.parse(file), uri);
              } else if (uri != null) {
                  refs = new $Refs(Parser.parse(uri), uri);
              } else {
                  refs = new $Refs(Parser.parse(json));
              }
              return this;
          }
     ```
  - to:
  ```java
       public $RefParser parse() throws IOException {
              if(file != null) {
                  refs = new $Refs(Parser.parse(file), uri);
              } else if (uri != null) {
                  refs = new $Refs(Parser.parse(uri), uri);
              } else {
                  refs = new $Refs(Parser.parse(json));
                  this.uri = new URI(".");
              }
              return this;
          }
    ```
    
 
Thanks!

**Comment by ivangsa** [comment]
Hi @JRDG 

thanks for the time you took on this detailed report... 

I will look in to fixing this soon
