### ISSUE TITLE
Which JSON Schema versions are supported?

### ISSUE THREAD

**Issue by jechterhoff** [ZenWave360/json-schema-ref-parser-jvm#3]
Hi.
Maybe I've missed that in the documentation, but can you tell us which JSON Schema versions (and their keywords) are supported by this tool?
Cheers,
Johannes

**Comment by jechterhoff** [comment]
... and is de-referencing of JSON Schema anchor-based references supported? Any insights would be appreciated.

Thanks,
Johannes

**Comment by ivangsa** [comment]
hi @jechterhoff 

it dereferences JSON Schema $ref pointers

Can you provide an example of what you mean by `anchor-based references`?

**Comment by ivangsa** [comment]
nop, those are not supported

**Comment by jechterhoff** [comment]
Ok, thanks.
